/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Database.Crud;
import Funciones.FTable;
import java.sql.ResultSet;
import javax.swing.table.TableModel;

/**
 *
 * @author LUCIANA
 */
public class ActContrato extends javax.swing.JPanel {

    /**
     * Creates new form ActContrato
     */
    Crud crud = new Crud();
    FTable ftable = new FTable();
    public ActContrato() {
        initComponents();
                String parametros[] = {};
        ResultSet datos = crud.SelectCondition("Select E.Nombre, E.ApellidoParterno + E.ApellidoMaterno As 'Apellidos', E.Dni, D.Nombre AS 'Departamento', c.Sede, c.Salario from Empleado E inner join Departamento D on D.IdDepartamento = E.IdDepartamento inner join Contrato C on c.IdContrato = e.IdEmpleado", parametros);
        ftable.InsertarDatos(tablaAC, datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        txtNombreAC = new javax.swing.JTextField();
        txtApellidoAC = new javax.swing.JTextField();
        txtDniAC = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        txtDepartamentoAC = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        txtSedeAC = new javax.swing.JTextField();
        jLabel95 = new javax.swing.JLabel();
        txtSalarioAC = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaAC = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(890, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Información Personal");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 850, 50));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(890, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Información Empresa");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 850, 50));

        jLabel86.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(0, 0, 0));
        jLabel86.setText("Apellidos");
        jPanel1.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 30));

        jLabel89.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(0, 0, 0));
        jLabel89.setText("Nombre");
        jPanel1.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabel91.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(0, 0, 0));
        jLabel91.setText("Dni");
        jPanel1.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, 30));

        txtNombreAC.setEditable(false);
        jPanel1.add(txtNombreAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, -1));

        txtApellidoAC.setEditable(false);
        jPanel1.add(txtApellidoAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 200, -1));

        txtDniAC.setEditable(false);
        jPanel1.add(txtDniAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 140, -1));

        jLabel93.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(0, 0, 0));
        jLabel93.setText("Departamento");
        jPanel1.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));
        jPanel1.add(txtDepartamentoAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 140, -1));

        jLabel94.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(0, 0, 0));
        jLabel94.setText("Sede");
        jPanel1.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 30));
        jPanel1.add(txtSedeAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, -1));

        jLabel95.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(0, 0, 0));
        jLabel95.setText("Salario");
        jPanel1.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, 30));
        jPanel1.add(txtSalarioAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 140, -1));

        tablaAC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dni", "Departamento", "Sede", "Salario"
            }
        ));
        tablaAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaACMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaAC);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 870, 220));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaACMouseClicked
        // TODO add your handling code here:
        int i = tablaAC.getSelectedRow();
        TableModel modelo = tablaAC.getModel();
        txtNombreAC.setText(modelo.getValueAt(i,0).toString());
        txtApellidoAC.setText(modelo.getValueAt(i,1).toString());
        txtDniAC.setText(modelo.getValueAt(i,2).toString());
        txtDepartamentoAC.setText(modelo.getValueAt(i,3).toString());
        txtSedeAC.setText(modelo.getValueAt(i,4).toString());
        txtSalarioAC.setText(modelo.getValueAt(i,5).toString());
    }//GEN-LAST:event_tablaACMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaAC;
    private javax.swing.JTextField txtApellidoAC;
    private javax.swing.JTextField txtDepartamentoAC;
    private javax.swing.JTextField txtDniAC;
    private javax.swing.JTextField txtNombreAC;
    private javax.swing.JTextField txtSalarioAC;
    private javax.swing.JTextField txtSedeAC;
    // End of variables declaration//GEN-END:variables
}
