/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Database.Crud;
import Funciones.FTable;
import java.sql.ResultSet;

import javax.swing.JButton;
import javax.swing.table.TableModel;

/**
 *
 * @author LUCIANA
 */
public class ActEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form ActEmpleado
     */
    Crud crud = new Crud();
    FTable ftable = new FTable();
    int column, row;
    public ActEmpleado() {
        initComponents();
        String parametros[] = {};
        ResultSet datos = crud.SelectCondition("exec DatosActEmp", parametros);
        JButton BtnDependiente = new JButton("Ver Dependiente");
        BtnDependiente.setName("btn1");
        JButton[] botones = {BtnDependiente};
        ftable.InsertarDatos(tablaAE, datos, botones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombreAE = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtApellidoAE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDniAE = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTelefonoAE = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEmailAE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNomViaAE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNumeroAE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAE = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnActualizarE = new javax.swing.JButton();
        comboViaAE = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(204, 0, 51));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Información Personal");
        jPanel18.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bg.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 40));

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Nombre");
        bg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        txtNombreAE.setEditable(false);
        txtNombreAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAEActionPerformed(evt);
            }
        });
        bg.add(txtNombreAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 220, 30));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Apellido");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 30));

        txtApellidoAE.setEditable(false);
        txtApellidoAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoAEActionPerformed(evt);
            }
        });
        bg.add(txtApellidoAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Dni");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        txtDniAE.setEditable(false);
        txtDniAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniAEActionPerformed(evt);
            }
        });
        bg.add(txtDniAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 220, 30));

        jPanel21.setBackground(new java.awt.Color(204, 0, 51));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Información Vivienda");
        jPanel21.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        bg.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 890, 40));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Telefono");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, 30));

        txtTelefonoAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoAEActionPerformed(evt);
            }
        });
        bg.add(txtTelefonoAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 160, 30));

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Email");
        bg.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 30));

        txtEmailAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAEActionPerformed(evt);
            }
        });
        bg.add(txtEmailAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 300, 30));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Tipo Via");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Nombre");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, 30));

        txtNomViaAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomViaAEActionPerformed(evt);
            }
        });
        bg.add(txtNomViaAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 160, 30));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Numero");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, 30));

        txtNumeroAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAEActionPerformed(evt);
            }
        });
        bg.add(txtNumeroAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 140, 30));

        tablaAE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Dni", "Telefono", "Correo", "Dirección", "Ver Dependiente "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaAE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAE);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 870, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ActualizarLog.jpg"))); // NOI18N
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -20, 190, 180));

        btnActualizarE.setText("ACTUALIZAR");
        btnActualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEActionPerformed(evt);
            }
        });
        bg.add(btnActualizarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, 30));

        comboViaAE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avenida", "Calle ", "Pasaje" }));
        bg.add(comboViaAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 160, 30));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAEActionPerformed

    private void txtApellidoAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoAEActionPerformed

    private void txtDniAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniAEActionPerformed

    private void txtTelefonoAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoAEActionPerformed

    private void txtEmailAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAEActionPerformed

    private void txtNomViaAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomViaAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomViaAEActionPerformed

    private void txtNumeroAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAEActionPerformed

    private void tablaAEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAEMouseClicked
        // TODO add your handling code here:
        int i = tablaAE.getSelectedRow();
        TableModel modelo = tablaAE.getModel();
        
        txtNombreAE.setText(modelo.getValueAt(i,0).toString());
        txtApellidoAE.setText(modelo.getValueAt(i,1).toString());
        txtDniAE.setText(modelo.getValueAt(i,2).toString());
        txtTelefonoAE.setText(modelo.getValueAt(i,3).toString());
        txtEmailAE.setText(modelo.getValueAt(i,4).toString());
        String[] direccion = (modelo.getValueAt(i,5).toString()).split(" ");
        String via = direccion[0];
            switch(via){
                case "Avenida" -> comboViaAE.setSelectedIndex(0);
                case "Calle" -> comboViaAE.setSelectedIndex(1);
                case "Pasaje" -> comboViaAE.setSelectedIndex(2);
            }
        String nombre;
        String num;
        
        if (direccion.length > 3){
            nombre = direccion[1] + " " + direccion[2];
            num = direccion[3] ;
        }
        else
        {
            nombre = direccion[1];
            num = direccion[2];
        }
        
        txtNomViaAE.setText(nombre);
        txtNumeroAE.setText(num);



        column = tablaAE.getColumnModel().getColumnIndexAtX(evt.getX());
        row = evt.getY()/tablaAE.getRowHeight();
        if(column <= tablaAE.getColumnCount() && column >= 0 && row <= tablaAE.getRowCount() && row >= 0){
            Object objeto = tablaAE.getValueAt(row, column);
            if(objeto instanceof JButton){
                ((JButton)objeto).doClick();
                JButton boton = (JButton) objeto;
                if(boton.getName() == "btn1"){
                    Object dni = tablaAE.getValueAt(row, 2);
                    VerDependiente ver = new VerDependiente(dni.toString());
                    ver.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_tablaAEMouseClicked

    private void btnActualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEActionPerformed
        // TODO add your handling code here:
        String dni =txtDniAE.getText();
        String email = txtEmailAE.getText();
        String telefono = txtTelefonoAE.getText();
        String via = comboViaAE.getSelectedItem().toString();
        String nomVia = txtNomViaAE.getText();
        String numero = txtNumeroAE.getText();
        
        String[] parametros = {dni, email, telefono, via, nomVia, numero};
        crud.UICondition("exec ActualizarEmp @Dni =? , @Email = ? , @Telefono =?, @Via = ?, @Nombre = ? , @Numero = ?", parametros);
        
        String param[] = {};
        ResultSet datos = crud.SelectCondition("exec DatosActEmp", param);
        JButton BtnDependiente = new JButton("Ver Dependiente");
        BtnDependiente.setName("btn1");
        JButton[] botones = {BtnDependiente};
        ftable.InsertarDatos(tablaAE, datos, botones);
    }//GEN-LAST:event_btnActualizarEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnActualizarE;
    private javax.swing.JComboBox<String> comboViaAE;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAE;
    private javax.swing.JTextField txtApellidoAE;
    private javax.swing.JTextField txtDniAE;
    private javax.swing.JTextField txtEmailAE;
    private javax.swing.JTextField txtNomViaAE;
    private javax.swing.JTextField txtNombreAE;
    private javax.swing.JTextField txtNumeroAE;
    private javax.swing.JTextField txtTelefonoAE;
    // End of variables declaration//GEN-END:variables
}
