/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;
import Database.Crud;
import Funciones.FTable;
import java.sql.ResultSet;
/**
 *
 * @author LUCIANA
 */
public class BonDes extends javax.swing.JPanel {

    /**
     * Creates new form BonDes
     */
    Crud crud = new Crud();
    FTable ftable = new FTable();
    public BonDes() {
        initComponents();
        String parametros[] = {};
        ResultSet datosBD = crud.SelectCondition("exec DatosBonDes", parametros);
        ftable.InsertarDatos(tablaBonDes, datosBD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBD = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtNombreBD = new javax.swing.JTextField();
        txtApellidoBD = new javax.swing.JTextField();
        comboMotivoBD = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        radioNoBD = new javax.swing.JRadioButton();
        radioSiBD = new javax.swing.JRadioButton();
        jLabel45 = new javax.swing.JLabel();
        radioDes = new javax.swing.JRadioButton();
        radioBon = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBonDes = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        comboBuscarBD = new javax.swing.JComboBox<>();
        txtDatoBD = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        bttnBuscarBD = new javax.swing.JButton();
        bttnAsignar = new javax.swing.JButton();
        btnMostrarBD = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 0, 51));
        jLabel40.setText("BonDes");
        jPanel16.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel41.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("Agregar un nuevo motivo");
        jPanel16.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 30));

        jLabel42.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/busqueda.png"))); // NOI18N
        jPanel16.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 30));

        jLabel43.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setText("Apellido");
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        txtNombreBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBDActionPerformed(evt);
            }
        });
        jPanel16.add(txtNombreBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, 30));

        txtApellidoBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoBDActionPerformed(evt);
            }
        });
        jPanel16.add(txtApellidoBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 220, 30));

        comboMotivoBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horas Extras", "Reparacion de Herramientas", "Limpieza General", "28 de Julio", "Navidad", "Asignacion Familiar", "Vacaciones", "Fallecimiento de algun familiar", "Enfermedad" }));
        jPanel16.add(comboMotivoBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 180, 30));

        jLabel44.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setText("Motivo");
        jPanel16.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 30));

        radioNoBD.setText("No");
        jPanel16.add(radioNoBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        radioSiBD.setText("Si");
        jPanel16.add(radioSiBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jLabel45.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setText("Nombre");
        jPanel16.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        grupoBD.add(radioDes);
        radioDes.setText("Descuento");
        radioDes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioDesMouseClicked(evt);
            }
        });
        radioDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesActionPerformed(evt);
            }
        });
        jPanel16.add(radioDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        grupoBD.add(radioBon);
        radioBon.setText("Bonificación");
        radioBon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioBonMouseClicked(evt);
            }
        });
        jPanel16.add(radioBon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        tablaBonDes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dni", "Salario", "Motivo", "Porcentaje", "Total", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaBonDes);

        jPanel16.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 840, 260));

        jLabel46.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 51, 51));
        jLabel46.setText("Tipo de Asignación:");
        jPanel16.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 30));

        jLabel47.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("Dato:");
        jPanel16.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 30));

        comboBuscarBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido", "Dni", " " }));
        jPanel16.add(comboBuscarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 150, 30));

        txtDatoBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoBDActionPerformed(evt);
            }
        });
        jPanel16.add(txtDatoBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 190, 30));

        jPanel25.setBackground(new java.awt.Color(204, 0, 51));

        jLabel48.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Busqueda y Filtros");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addContainerGap(664, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel48)
                .addContainerGap())
        );

        jPanel16.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 850, 40));

        jLabel52.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));
        jLabel52.setText("  Buscar por");
        jPanel16.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        jLabel54.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 51));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BondesLog.jpg"))); // NOI18N
        jPanel16.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 110));

        bttnBuscarBD.setText("BUSCAR");
        bttnBuscarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBuscarBDActionPerformed(evt);
            }
        });
        jPanel16.add(bttnBuscarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 90, 30));

        bttnAsignar.setText("ASIGNAR");
        bttnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAsignarActionPerformed(evt);
            }
        });
        jPanel16.add(bttnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 90, 30));

        btnMostrarBD.setText("MOSTRAR");
        btnMostrarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarBDActionPerformed(evt);
            }
        });
        jPanel16.add(btnMostrarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 90, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBDActionPerformed

    private void txtApellidoBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoBDActionPerformed

    private void radioDesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioDesMouseClicked
        // TODO add your handling code here:
        String parametros[] = {};
        ResultSet datosD = crud.SelectCondition("exec DatosDes", parametros);
        ftable.InsertarDatos(tablaBonDes, datosD);
        actualizarDes();
    }//GEN-LAST:event_radioDesMouseClicked

    private void radioDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDesActionPerformed

    private void radioBonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBonMouseClicked
        // TODO add your handling code here:
        String parametros[] = {};
        ResultSet datosB = crud.SelectCondition("exec DatosBonDes", parametros);
        ftable.InsertarDatos(tablaBonDes, datosB);
        actualizarBon();
    }//GEN-LAST:event_radioBonMouseClicked

    private void actualizarBon(){
        comboMotivoBD.removeAllItems(); 
        comboMotivoBD.addItem("Horas Extras");
        comboMotivoBD.addItem("Reparacion de Herramientas");
        comboMotivoBD.addItem("Limpieza General");
        comboMotivoBD.addItem("28 de Julio");
        comboMotivoBD.addItem("Navidad");
        comboMotivoBD.addItem("Asignacion Familiar");
        comboMotivoBD.addItem("Vacaciones");
        comboMotivoBD.addItem("Fallecimiento de algun familiar");
        comboMotivoBD.addItem("Enfermedad");
    }
    
    private void actualizarDes(){
        comboMotivoBD.removeAllItems(); 
        comboMotivoBD.addItem("Afp Integra");
        comboMotivoBD.addItem("Afp Prima");
        comboMotivoBD.addItem("Afp Habitat");
        comboMotivoBD.addItem("Mal uso de herramientas");
        comboMotivoBD.addItem("Seguro Privado");
        comboMotivoBD.addItem("Falta No Justificada");

    }
    
    
    
    
    private void txtDatoBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoBDActionPerformed

    private void bttnBuscarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBuscarBDActionPerformed
        // TODO add your handling code here:
        if(radioDes.isSelected()){
            String combo = comboBuscarBD.getSelectedItem().toString();
            String buscar = txtDatoBD.getText();
            String parametros[] = {buscar};
            switch (combo){
                case "Nombre" -> {
                    ResultSet datosN = crud.SelectCondition("exec BuscarDesNombre @Nombre = ?", parametros);
                    ftable.InsertarDatos(tablaBonDes, datosN);
                }
                case "Apellido" -> {
                    ResultSet datosA = crud.SelectCondition("exec BuscarDesApellido @Apellido = ?", parametros);
                    ftable.InsertarDatos(tablaBonDes, datosA);
                }
                case "Dni" -> {
                    ResultSet datosD = crud.SelectCondition("exec BuscarDesDni @Dni = ?", parametros);
                    ftable.InsertarDatos(tablaBonDes, datosD);
                }
            }
        }
        else if(radioBon.isSelected()){
            String combo = comboBuscarBD.getSelectedItem().toString();
            String buscar = txtDatoBD.getText();
            String parametros[] = {buscar};
            switch (combo){
                case "Nombre" -> {
                    ResultSet datosN = crud.SelectCondition("exec BuscarBonNombre @Nombre = ?", parametros);
                    ftable.InsertarDatos(tablaBonDes, datosN);
                }
                case "Apellido" -> {
                    ResultSet datosA = crud.SelectCondition("exec BuscarBonApellido @Apellido = ?", parametros);
                    ftable.InsertarDatos(tablaBonDes, datosA);
                }
                case "Dni" -> {
                    ResultSet datosD = crud.SelectCondition("exec BuscarBonDni @Dni = ?", parametros);
                    ftable.InsertarDatos(tablaBonDes, datosD);
                }
            }
        }
    }//GEN-LAST:event_bttnBuscarBDActionPerformed

    private void btnMostrarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarBDActionPerformed
        // TODO add your handling code here:
        if(radioBon.isSelected()){
            String parametros[] = {};
            ResultSet datosBD = crud.SelectCondition("exec DatosBonDes", parametros);
            ftable.InsertarDatos(tablaBonDes, datosBD);
        }
        else if (radioDes.isSelected()){
            String parametros[] = {};
            ResultSet datosD = crud.SelectCondition("exec DatosDes", parametros);
            ftable.InsertarDatos(tablaBonDes, datosD);
        }
    }//GEN-LAST:event_btnMostrarBDActionPerformed

    private void bttnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarBD;
    private javax.swing.JButton bttnAsignar;
    private javax.swing.JButton bttnBuscarBD;
    private javax.swing.JComboBox<String> comboBuscarBD;
    private javax.swing.JComboBox<String> comboMotivoBD;
    private javax.swing.ButtonGroup grupoBD;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioBon;
    private javax.swing.JRadioButton radioDes;
    private javax.swing.JRadioButton radioNoBD;
    private javax.swing.JRadioButton radioSiBD;
    private javax.swing.JTable tablaBonDes;
    private javax.swing.JTextField txtApellidoBD;
    private javax.swing.JTextField txtDatoBD;
    private javax.swing.JTextField txtNombreBD;
    // End of variables declaration//GEN-END:variables
}
