/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

/**
 *
 * @author laszlo
 */
public class CAsistencia extends javax.swing.JPanel {

    /**
     * Creates new form CAsistencia
     */
    public CAsistencia(String Nombre) {
        initComponents();
        System.out.println(Nombre);
        LBNombre.setText(Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        LBNombre = new javax.swing.JLabel();
        RAsistio = new javax.swing.JRadioButton();
        RTardanza = new javax.swing.JRadioButton();
        RFalta = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        LBNombre.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        LBNombre.setText("Nombre");

        Grupo1.add(RAsistio);
        RAsistio.setText("Asistio");

        Grupo1.add(RTardanza);
        RTardanza.setText("Tardanza");

        Grupo1.add(RFalta);
        RFalta.setText("Falto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RAsistio)
                .addGap(43, 43, 43)
                .addComponent(RTardanza)
                .addGap(35, 35, 35)
                .addComponent(RFalta)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RTardanza)
                    .addComponent(RAsistio)
                    .addComponent(RFalta)
                    .addComponent(LBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public String getAsistencia(){
        if(RAsistio.isSelected()){
            return RAsistio.getText();
        }else if(RTardanza.isSelected()){
            return RTardanza.getText();
        }else if(RFalta.isSelected()){
            return RFalta.getText();
        }else{
            return "Ningun Seleccionado";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JLabel LBNombre;
    private javax.swing.JRadioButton RAsistio;
    private javax.swing.JRadioButton RFalta;
    private javax.swing.JRadioButton RTardanza;
    // End of variables declaration//GEN-END:variables
}
