/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

/**
 *
 * @author laszlo
 */
public class CAsistencia extends javax.swing.JPanel {

    /**
     * Creates new form CAsistencia
     */
    public CAsistencia(String Nombre) {
        initComponents();
        System.out.println("hola");
        LBNombre.setText(Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        LBNombre = new javax.swing.JLabel();
        RAsistio = new javax.swing.JRadioButton();
        RTardanza = new javax.swing.JRadioButton();
        RFalta = new javax.swing.JRadioButton();

        LBNombre.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        LBNombre.setText("Nombre");

        Grupo1.add(RAsistio);
        RAsistio.setText("Asistio");

        Grupo1.add(RTardanza);
        RTardanza.setText("Tardanza");

        Grupo1.add(RFalta);
        RFalta.setText("Falto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(LBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(RAsistio)
                .addGap(42, 42, 42)
                .addComponent(RTardanza)
                .addGap(41, 41, 41)
                .addComponent(RFalta)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RAsistio)
                    .addComponent(RTardanza)
                    .addComponent(RFalta))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JLabel LBNombre;
    private javax.swing.JRadioButton RAsistio;
    private javax.swing.JRadioButton RFalta;
    private javax.swing.JRadioButton RTardanza;
    // End of variables declaration//GEN-END:variables
}
