/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Database.Crud;
import Funciones.FTable;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.ResultSet;
import java.util.Date;

/**
 *
 * @author LUCIANA
 */
public class Contratos extends javax.swing.JPanel {

    /**
     * Creates new form Contratos
     */
        Crud crud = new Crud();
    FTable ftable = new FTable();
    String ruta_archivo = "";
    public Contratos() {
        initComponents();
        String parametros[] = {};
        ResultSet datosC = crud.SelectCondition("exec DatosContratos", parametros);
        ftable.InsertarDatos(tablaC, datosC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel29 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        txtDatoC = new javax.swing.JTextField();
        comboBuscarC = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaC = new javax.swing.JTable();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        btnSeleccionarC = new javax.swing.JButton();
        txtSalarioC = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        txtApellidosC = new javax.swing.JTextField();
        txtDniC = new javax.swing.JTextField();
        txtSedeC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnBuscarC = new javax.swing.JButton();
        jLabel96 = new javax.swing.JLabel();
        dateFechaInicioC = new com.toedter.calendar.JDateChooser();
        jLabel97 = new javax.swing.JLabel();
        dateFechaFin = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel85.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(204, 0, 51));
        jLabel85.setText("Contratos");
        jPanel29.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel49.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/busqueda.png"))); // NOI18N
        jPanel29.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel51.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel51.setText("Dato");
        jPanel29.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, 30));

        jLabel86.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(51, 51, 51));
        jLabel86.setText("Apellidos");
        jPanel29.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 30));
        jPanel29.add(txtDatoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 190, -1));

        comboBuscarC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Dni", "Departamento" }));
        jPanel29.add(comboBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 170, -1));

        tablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dni", "Departamento", "Sede", "Salario"
            }
        ));
        jScrollPane5.setViewportView(tablaC);

        jPanel29.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 870, 220));

        jLabel87.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel87.setText("Buscar por:");
        jPanel29.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 30));

        jLabel88.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(51, 51, 51));
        jLabel88.setText("Archivo");
        jPanel29.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, 30));

        jLabel89.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(51, 51, 51));
        jLabel89.setText("Nombre");
        jPanel29.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        jLabel91.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(51, 51, 51));
        jLabel91.setText("Dni");
        jPanel29.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, 30));

        jLabel94.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(51, 51, 51));
        jLabel94.setText("Sede");
        jPanel29.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel95.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(51, 51, 51));
        jLabel95.setText("Fecha Fin");
        jPanel29.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        btnSeleccionarC.setText("Seleccionar...");
        btnSeleccionarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCActionPerformed(evt);
            }
        });
        jPanel29.add(btnSeleccionarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 280, 30));
        jPanel29.add(txtSalarioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, -1));
        jPanel29.add(txtNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, -1));
        jPanel29.add(txtApellidosC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 200, -1));
        jPanel29.add(txtDniC, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 140, -1));
        jPanel29.add(txtSedeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 140, -1));

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(890, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Información Personal");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel29.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 870, 40));

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(890, 40));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Información Empresarial");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addContainerGap(621, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel29.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 870, 40));

        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel29.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 90, 30));

        btnBuscarC.setText("BUSCAR");
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });
        jPanel29.add(btnBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 80, 30));

        jLabel96.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(51, 51, 51));
        jLabel96.setText("Salario");
        jPanel29.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, 30));
        jPanel29.add(dateFechaInicioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 190, -1));

        jLabel97.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(51, 51, 51));
        jLabel97.setText("Fecha Inicio");
        jPanel29.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, 30));
        jPanel29.add(dateFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 190, -1));

        add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            this.btnSeleccionarC.setText("" + j.getSelectedFile().getName());
            ruta_archivo = j.getSelectedFile().getAbsolutePath();

        } else {
        }
    }//GEN-LAST:event_btnSeleccionarCActionPerformed

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        // TODO add your handling code here:
        String combo = comboBuscarC.getSelectedItem().toString();
        String buscar = txtDatoC.getText();
        String parametros[] = {buscar};
        switch (combo){
            case "Nombre" -> {
                ResultSet datosN = crud.SelectCondition("exec BuscarContNombre @Nombre = ?", parametros);
                ftable.InsertarDatos(tablaC, datosN);
            }
            case "Dni" -> {
                ResultSet datosD = crud.SelectCondition("exec BuscarContDni @Dni = ?", parametros);
                ftable.InsertarDatos(tablaC, datosD);
            }
            case "Departamento" -> {
                ResultSet datosDE = crud.SelectCondition("exec BuscarContDepa @Departamento = ?", parametros);
                ftable.InsertarDatos(tablaC, datosDE);
            }
        }
    }//GEN-LAST:event_btnBuscarCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //falta las fechas xddd
        String nombre = txtNombreC.getText();
        Date FechaInicio = dateFechaInicioC.getDate();
        Date FechaFin = dateFechaFin.getDate();
        String Sede = txtSedeC.getText();
        int Salario = Integer.parseInt(txtSalarioC.getText());
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnSeleccionarC;
    private javax.swing.JComboBox<String> comboBuscarC;
    private com.toedter.calendar.JDateChooser dateFechaFin;
    private com.toedter.calendar.JDateChooser dateFechaInicioC;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaC;
    private javax.swing.JTextField txtApellidosC;
    private javax.swing.JTextField txtDatoC;
    private javax.swing.JTextField txtDniC;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtSalarioC;
    private javax.swing.JTextField txtSedeC;
    // End of variables declaration//GEN-END:variables
}
