/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Database.Crud;
import Funciones.FTable;
import javax.swing.JButton;
import java.sql.ResultSet;

/**
 *
 * @author LUCIANA
 */
public class Empleado extends javax.swing.JPanel {

    /**
     * Creates new form Empleado
     */
    int columna, row;
     Crud crud = new Crud();
    FTable ftable = new FTable();
    public Empleado() {
        initComponents();
        JButton BtnDependiente = new JButton("Ver Dependiente");
        BtnDependiente.setName("btn1");
        JButton[] botones = {BtnDependiente};
        String parametros[] = {};
        ResultSet datosE = crud.SelectCondition("exec DatosEmpleado", parametros);
        ftable.InsertarDatos(tablaEmp, datosE, botones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEmp = new javax.swing.JTable();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        comboBuscarE = new javax.swing.JComboBox<>();
        jLabel84 = new javax.swing.JLabel();
        txtDatoE = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnBuscarE = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel75.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(204, 0, 51));
        jLabel75.setText("Empleados");
        jPanel26.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tablaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Dni", "Telefono", "Correo", "Direccion", "Departamento", "Ver Dependientes"
            }
        ));
        tablaEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaEmp);

        jPanel26.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 900, 220));

        jLabel77.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(51, 51, 51));
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/busqueda.png"))); // NOI18N
        jPanel26.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        jLabel78.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(51, 51, 51));
        jLabel78.setText("  Buscar por");
        jPanel26.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));

        comboBuscarE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido", "Dni", "Departamento" }));
        jPanel26.add(comboBuscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 150, 30));

        jLabel84.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(51, 51, 51));
        jLabel84.setText("Dato:");
        jPanel26.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 30));

        txtDatoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoEActionPerformed(evt);
            }
        });
        jPanel26.add(txtDatoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 220, 30));

        btnMostrar.setText("MOSTRAR TODO");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel26.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 30));

        btnBuscarE.setText("BUSCAR");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });
        jPanel26.add(btnBuscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 80, 30));

        add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpMouseClicked
        columna = tablaEmp.getColumnModel().getColumnIndexAtX(evt.getX());
        row = evt.getY()/tablaEmp.getRowHeight();
        if(columna <= tablaEmp.getColumnCount() && columna >=0 && row <= tablaEmp.getRowCount() && row >=0){
            Object objeto = tablaEmp.getValueAt(row, columna);
            if(objeto instanceof JButton){
                ((JButton)objeto).doClick();
                JButton boton = (JButton) objeto;
                if(boton.getName() == "btn1"){
                    Object dni = tablaEmp.getValueAt(row, 2);
                    System.out.println(dni.toString());
                    VerDependiente ver = new VerDependiente(dni.toString());
                    ver.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_tablaEmpMouseClicked

    private void txtDatoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoEActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        JButton BtnDependiente = new JButton("Ver Dependiente");
        BtnDependiente.setName("btn1");
        JButton[] botones = {BtnDependiente};
        String parametros[] = {};
        ResultSet datosE = crud.SelectCondition("exec DatosEmpleado", parametros);
        ftable.InsertarDatos(tablaEmp, datosE);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        // TODO add your handling code here:
        String combo = comboBuscarE.getSelectedItem().toString();
        String buscar = txtDatoE.getText();
        String parametros[] = {buscar};
        switch (combo){
            case "Nombre" -> {
                ResultSet datosN = crud.SelectCondition("exec BuscarEmpNombre @Nombre =?", parametros);
                ftable.InsertarDatos(tablaEmp, datosN);
            }
            case "Apellido" -> {
                ResultSet datosA = crud.SelectCondition("exec BuscarEmpApellido @Apellido = ?", parametros);
                ftable.InsertarDatos(tablaEmp, datosA);
            }
            case "Dni" -> {
                ResultSet datosD = crud.SelectCondition("exec BuscarEmpDni @Dni = ?", parametros);
                ftable.InsertarDatos(tablaEmp, datosD);
            }
            case "Departamento" -> {
                ResultSet datosDE = crud.SelectCondition("Select E.Nombre,E.ApellidoPaterno + E.ApellidoMaterno As 'Apellidos', E.Dni, E.Telefono, U.email, C.TipoVia + C.Nombre + CAST(C.Numero as varchar) AS 'Direccion', D.Nombre as 'Departamento' from Empleado E inner join Usuario U on U.IdUsuario = E.IdUsuario inner join Direccion C on C.IdDireccion = E.IdDireccion inner join Departamento D on D.IdDepartamento = E.IdDepartamento Where D.Nombre = ?", parametros);
                ftable.InsertarDatos(tablaEmp, datosDE);
            }
        }
    }//GEN-LAST:event_btnBuscarEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> comboBuscarE;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaEmp;
    private javax.swing.JTextField txtDatoE;
    // End of variables declaration//GEN-END:variables
}
