/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Database.Crud;
import Funciones.FTable;
import java.sql.ResultSet;

/**
 *
 * @author LUCIANA
 */
public class Pagos extends javax.swing.JPanel {

    /**
     * Creates new form Pagos
     */
    Crud crud = new Crud();
    FTable ftable = new FTable();
    public Pagos() {
        initComponents();
        String parametros[] = {};
        ResultSet datosPG = crud.SelectCondition("exec DatosPagos", parametros);
        ftable.InsertarDatos(tablaPG, datosPG);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPG = new javax.swing.JTable();
        jLabel76 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        comboNomP = new javax.swing.JComboBox<>();
        txtDatoP = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(204, 0, 51));
        jLabel56.setText("Empleados");
        jPanel15.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jPanel27.setBackground(new java.awt.Color(221, 221, 221));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(51, 51, 51));
        jLabel57.setText("S/. XXXXXXXX");
        jPanel27.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 30));

        jLabel58.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(51, 51, 51));
        jLabel58.setText("Descuentos");
        jPanel27.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 30));

        jLabel59.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(51, 51, 51));
        jLabel59.setText("Total a Pagar por Periodo");
        jPanel27.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel60.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(51, 51, 51));
        jLabel60.setText("Detallado");
        jPanel27.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel61.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(51, 51, 51));
        jLabel61.setText("Bruto");
        jPanel27.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel62.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(51, 51, 51));
        jLabel62.setText("Beneficios");
        jPanel27.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 30));

        jLabel63.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(51, 51, 51));
        jLabel63.setText("S/. XXXXXXXX");
        jPanel27.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 30));

        jLabel64.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 51, 51));
        jLabel64.setText("S/. XXXXXXXX");
        jPanel27.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel65.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(51, 51, 51));
        jLabel65.setText("S/. XXXXXXXX");
        jPanel27.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 30));

        jPanel15.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 380, 190));

        jPanel28.setBackground(new java.awt.Color(204, 0, 51));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("S/. XXXXXXXX");
        jPanel28.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 30));

        jLabel67.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Descuentos");
        jPanel28.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 30));

        jLabel68.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Total Pagado el Año");
        jPanel28.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel69.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Detallado");
        jPanel28.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel70.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Bruto");
        jPanel28.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel71.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Beneficios");
        jPanel28.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 30));

        jLabel72.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("S/. XXXXXXXX");
        jPanel28.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 30));

        jLabel73.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("S/. XXXXXXXX");
        jPanel28.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel74.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("S/. XXXXXXXX");
        jPanel28.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 30));

        jPanel15.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 380, 190));

        tablaPG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Dni", "Departamento", "Salario", "Beneficios", "Descuentos", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaPG);

        jPanel15.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 770, 180));

        jLabel76.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(204, 0, 51));
        jLabel76.setText("Pagos");
        jPanel15.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel79.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(51, 51, 51));
        jLabel79.setText("  Buscar por");
        jPanel15.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, 20));

        comboNomP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido", "Dni" }));
        jPanel15.add(comboNomP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 150, 30));

        txtDatoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoPActionPerformed(evt);
            }
        });
        jPanel15.add(txtDatoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 220, 30));

        jLabel81.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(51, 51, 51));
        jLabel81.setText("Dato:");
        jPanel15.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, 30));

        jLabel83.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(51, 51, 51));
        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/busqueda.png"))); // NOI18N
        jPanel15.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, 30));

        add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboNomP;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaPG;
    private javax.swing.JTextField txtDatoP;
    // End of variables declaration//GEN-END:variables
}
